In [86]:
import pandas as pd;
import numpy as np;

In [87]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print (a[0], a[1], a[2])
a[0]=5
print (a)

b=np.array([[1,2,3],
            [4,5,6]])
print(b)
print(b.shape)
print(b[0,0])

c=np.array([1.0,2.1,3.4])
print(c)

[1 2 3]
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1
[1.  2.1 3.4]


In [88]:
a = np.zeros((2,3))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,3), 7)
print(c)

e = np.random.random((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.30574529 0.35769305 0.5442511 ]
 [0.22200135 0.97431655 0.49059487]
 [0.55137506 0.91032703 0.46568841]]


In [89]:
a = np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
print(a)

b=a[:2, 1:3]
print(b)

print(a[0,1])
b[0,0]=75
print(a[0,1])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
75
[[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:
a = np.array([[1,2],
             [2,4],
             [5,6]])
print(a)
print(a>2)
print(a[a>2])

[[1 2]
 [2 4]
 [5 6]]
[[False False]
 [False  True]
 [ True  True]]
[4 5 6]


In [91]:
x=np.array([[1,2],
          [3,4]])
y=np.array([[5,6],
          [7,8]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
      
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [92]:
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [93]:
s = pd.Series(['John', 'Rich', 'Michael', 'Sue', 'Kath'])
#print(s)
#print(s[0])
#print(s[1:4])
#print(s[[0,1,3]])

param = s != 'John'
print(s[param])

1       Rich
2    Michael
3        Sue
4       Kath
dtype: object


In [94]:
d = {'New York': 1300,
     'Chicago' : 900,
     'San Francisco' : 1100,
     'Austin' : 450    
}
cities = pd.Series(d)
print(cities)


New York         1300
Chicago           900
San Francisco    1100
Austin            450
dtype: int64


In [95]:
cities[['Chicago', 'San Francisco']]

Chicago           900
San Francisco    1100
dtype: int64

In [96]:
#Total population under 1000
cities[cities < 1000]

Chicago    900
Austin     450
dtype: int64

In [97]:
#Total population under 1000
cities[cities > 1000]

New York         1300
San Francisco    1100
dtype: int64

In [98]:
cities[cities < 1000] = 750
print(cities)

New York         1300
Chicago           750
San Francisco    1100
Austin            750
dtype: int64


In [101]:
titanic = pd.read_csv('Titanic.txt', sep='\t')
print(titanic.head())

  pclass    age   sex survived
0    1st  adult  male      yes
1    1st  adult  male      yes
2    1st  adult  male      yes
3    1st  adult  male      yes
4    1st  adult  male      yes


In [105]:
titanic['age']

0       adult
1       adult
2       adult
3       adult
4       adult
        ...  
2196    adult
2197    adult
2198    adult
2199    adult
2200    adult
Name: age, Length: 2201, dtype: object

In [106]:
titanic[['age', 'pclass']]

age pclass
0     adult    1st
1     adult    1st
2     adult    1st
3     adult    1st
4     adult    1st
...     ...    ...
2196  adult   crew
2197  adult   crew
2198  adult   crew
2199  adult   crew
2200  adult   crew

[2201 rows x 2 columns]

In [108]:
titanic[(titanic.age=='child') & (titanic.pclass=='2nd')]

pclass    age     sex survived
586    2nd  child    male      yes
587    2nd  child    male      yes
588    2nd  child    male      yes
589    2nd  child    male      yes
590    2nd  child    male      yes
591    2nd  child    male      yes
592    2nd  child    male      yes
593    2nd  child    male      yes
594    2nd  child    male      yes
595    2nd  child    male      yes
596    2nd  child    male      yes
597    2nd  child  female      yes
598    2nd  child  female      yes
599    2nd  child  female      yes
600    2nd  child  female      yes
601    2nd  child  female      yes
602    2nd  child  female      yes
603    2nd  child  female      yes
604    2nd  child  female      yes
605    2nd  child  female      yes
606    2nd  child  female      yes
607    2nd  child  female      yes
608    2nd  child  female      yes
609    2nd  child  female      yes

In [109]:
titanic[320:330]

pclass    age     sex survived
320    1st  child    male      yes
321    1st  child    male      yes
322    1st  child    male      yes
323    1st  child    male      yes
324    1st  child  female      yes
325    2nd  adult    male      yes
326    2nd  adult    male      yes
327    2nd  adult    male      yes
328    2nd  adult    male      yes
329    2nd  adult    male      yes

In [117]:
by_age=titanic.groupby('age')
by_age.size()

age
adult    2092
child     109
dtype: int64

In [120]:
print(titanic.groupby(['sex']).size())
print(titanic.groupby(['survived', 'sex']).size())


sex
female     470
male      1731
dtype: int64
survived  sex   
no        female     126
          male      1364
yes       female     344
          male       367
dtype: int64


In [ ]:
#And Data Analysis